name: Sink Lint and Test

on:
  workflow_run:
    workflows: ["Pre-commit"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.triple.runs-on }}
    strategy:
      matrix:
        triple:
          - runs-on: ubuntu-22.04
            target: x86-unknown-linux-gnu
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # 3.6.0

      - name: Install libzmq
        run: |
          sudo apt -q update
          sudo apt -qy --no-install-recommends install libzmq3-dev

      - name: Setup Rust
        run: |
          set -e
          rustup toolchain install stable --no-self-update --profile minimal --component rustfmt
          rustup default stable

      - name: Cache deps
        uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4  # 2.6.2
        with:
          key: ${{ matrix.triple.runs-on }}

      - name: Run tests
        run: cargo test --no-fail-fast

  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ${{ matrix.triple.runs-on }}
    steps:
      - run: echo 'Pre-commit failed'
